// app/book/styles.ts
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    paddingBottom: 30,
  },

  content: {
    width: "100%",
    paddingHorizontal: 12,
    paddingTop: 16,
    maxWidth: 950,
    alignSelf: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "stretch",
  },

  headerContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    maxWidth: 950,
    paddingHorizontal: 20,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    borderBottomEndRadius: 8,
    borderBottomStartRadius: 8,
    paddingTop: 20,
    paddingBottom: 12,
  },
  scrollContent: {
    flexGrow: 1,
  },
  header: {
    width: "100%",
    maxWidth: 900,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f5f5f5",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
  },
  imageSection: {
    alignItems: "center",
    marginBottom: 12,
    borderRadius: 8,
    overflow: "hidden",
  },
  imageWrapper: {
    position: "relative",
  },
  detailImage: {
    width: "100%",
    height: "100%",
  },
  noImage: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
  },
  discountBadge: {
    position: "absolute",
    right: 0,
    backgroundColor: "#f44336",
    paddingHorizontal: 24,
    paddingVertical: 6,

    borderBottomStartRadius: 20,
  },
  discountBadgeText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "bold",
  },
  titleSection: {
    alignItems: "center",
    marginBottom: 12,
  },
  bookTitle: {
    fontWeight: "bold",
    color: "#1a1a1a",
    textAlign: "center",
  },
  authorWrapper: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  bookAuthor: {
    fontSize: 15,
    color: "#999",
  },
  priceSection: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  priceWrapper: {
    alignItems: "center",
    marginBottom: 12,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  oldPrice: {
    fontSize: 14,
    color: "#999",
    textDecorationLine: "line-through",
    marginBottom: 4,
  },
  finalPrice: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#4CAF50",
  },
  singlePrice: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#333",
  },
  actionButtons: {
    flexDirection: "row",
    gap: 12,
  },
  cartButton: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#4CAF50",
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  cartButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  disabledButton: {
    backgroundColor: "#ccc",
  },
  wishlistButton: {
    width: 52,
    height: 52,
    borderRadius: 8,
    backgroundColor: "#f5f5f5",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#e8e8e8",
  },
  audioButton: {
    width: 52,
    height: 52,
    borderRadius: 8,
    backgroundColor: "#f5f5f5",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#9C27B0",
  },
  wishlistActive: {
    backgroundColor: "#fff0f0",
    borderColor: "#f44336",
  },
  commentlistActive: {
    borderColor: "#189deb",
  },
  infoCard: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 12,
  },
  infoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
  },
  infoItem: {
    flexDirection: "row",
    alignItems: "center",
  },
  infoIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#f0f8f0",
    alignItems: "center",
    justifyContent: "center",
  },
  infoText: {
    flex: 1,
    flexDirection: "row",
    gap: 16,
  },
  infoLabel: {
    fontSize: 12,
    color: "#999",
    marginRight: 16,
    marginBottom: 2,
  },
  infoValue: {
    fontSize: 14,
    color: "#333",
    fontWeight: "500",
  },
  inStock: {
    color: "#4CAF50",
  },
  outOfStock: {
    color: "#f44336",
  },
  descriptionCard: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 16,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    width: "100%",
  },
  descriptionText: {
    fontSize: 14,
    color: "#555",
    lineHeight: 24,
    textAlign: "justify",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: "#999",
  },
  // حالت خطا
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
    padding: 24,
  },
  errorIcon: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "#f5f5f5",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  errorTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 8,
  },
  errorText: {
    fontSize: 14,
    color: "#999",
    textAlign: "center",
    marginBottom: 24,
  },
  errorBackButton: {
    flexDirection: "row",
    backgroundColor: "#4CAF50",
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderRadius: 30,
    alignItems: "center",
    gap: 8,
  },
  errorBackText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  sectionNavbar: {
    flexDirection: "row",
    width: "100%",
    borderBottomWidth: 2,
    borderBottomColor: "#e2e2e2",
    marginBottom: 12,
  },
  sectionNavbarItems: {
    borderBottomColor: "orange",
    borderBottomWidth: 2,
    marginHorizontal: 8,
    paddingHorizontal: 8,
  },
  commentsCard: {
    backgroundColor: "#fff",
    borderRadius: 8,
    overflow: "hidden",
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
    width: "100%",
    flexWrap: "wrap",
  },
});
