import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  content: {
    padding: 20,
    width: "100%",
    alignSelf: "center",
    maxWidth: 500,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
    marginBottom: 30,
    marginTop: 20,
  },
  label: {
    fontSize: 16,
    fontWeight: "600",
    color: "#555",
    marginBottom: 8,
    marginTop: 10,
  },
  input: {
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 15,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#ddd",
    textAlign: "right",
  },
  codeHint: {
    fontSize: 14,
    color: "#666",
    marginBottom: 20,
    textAlign: "right",
  },
  findButton: {
    backgroundColor: "#4CAF50",
    borderRadius: 10,
    padding: 10,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    flexGrow: 1,
  },
  qrButton: {
    backgroundColor: "#2196F3",
    borderRadius: 10,
    padding: 10,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  bookInfoContainer: {
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 20,
    marginTop: 20,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  bookInfoTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 15,
    textAlign: "center",
  },
  bookInfoText: {
    fontSize: 14,
    color: "#555",
    marginBottom: 8,
    textAlign: "right",
  },
  bookPageBtn: {
    backgroundColor: "#2196F3",
    borderRadius: 10,
    padding: 10,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: "auto",
    paddingHorizontal: 40,
    marginTop: 15,
  },

  bookHeader: {
    flexDirection: "row",
    gap: 15,
    marginBottom: 20,
  },
  bookImage: {
    width: 150,
    height: 150 * 1.4,
    borderRadius: 8,
    backgroundColor: "#f0f0f0",
  },
  noImage: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
  },
  bookDetails: {
    flex: 1,
    justifyContent: "center",
  },
  boldText: {
    fontWeight: "bold",
    color: "#333",
  },
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: "#666",
  },
});
