// components/pages/Basket/styles.ts

import { StyleSheet } from "react-native";
import { shadow } from "@/utils/shadow";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    padding: 20,
    width: "100%",
    maxWidth: 1000,
    marginHorizontal: "auto",
  },
  layout: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 16,
  },
  layoutMobile: {
    flexDirection: "column",
  },
  listCard: {
    flex: 1,
    minWidth: 0,
    backgroundColor: "#fff",
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    overflow: "hidden",
    ...shadow("#000", { width: 0, height: 2 }, 0.05, 8, 3),
  },
  listColumn: {
    flex: 1,
    minWidth: 0,
    gap: 12,
  },
  unavailableBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: "rgba(255, 59, 48, 0.2)",
    borderWidth: 1,
    borderColor: "rgba(255, 59, 48, 0.5)",
    borderRadius: 12,
  },
  unavailableBannerText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 20,
    color: "#7A1010",
  },
  unavailableBannerButton: {
    backgroundColor: "#FF3B30",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 14,
    flexShrink: 0,
  },
  unavailableBannerButtonText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "bold",
  },
  sidebar: {
    width: 340,
    flexShrink: 0,
    position: "sticky",
    top: 20,
    alignSelf: "flex-start",
    zIndex: 2,
  },
  sidebarMobile: {
    width: "100%",
  },
  listHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  listTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  itemsCount: {
    fontSize: 13,
    color: "#999",
  },
  cartItem: {
    flexDirection: "row",
    alignItems: "stretch",
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    overflow: "hidden",
    minHeight: 200,
    paddingVertical: 20,
  },
  imageWrap: {
    width: 120,
    alignSelf: "stretch",
    marginRight: 20,
    borderRadius: 8,
    overflow: "hidden",
  },
  productImage: {
    width: "100%",
    height: "100%",
    backgroundColor: "#f5f5f5",
  },
  productImagePlaceholder: {
    alignItems: "center",
    justifyContent: "center",
  },
  itemMain: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 16,
    paddingHorizontal: 14,
  },
  itemTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 6,
  },
  itemMeta: {
    fontSize: 13,
    color: "#999",
    marginBottom: 4,
  },
  outOfStock: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FF3B30",
    marginTop: 4,
  },
  itemSide: {
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 16,
    minWidth: 140,
  },
  itemSideUnavailable: {
    justifyContent: "flex-end",
  },
  itemPrice: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#007AFF",
  },
  itemCurrency: {
    fontSize: 13,
    fontWeight: "600",
    color: "#007AFF",
  },
  itemPriceBlock: {
    alignItems: "flex-end",
    gap: 2,
  },
  itemDiscountRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
  },
  itemDiscountBadge: {
    backgroundColor: "#EF4056",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    paddingTop: 3,
  },
  itemDiscountBadgeText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "bold",
    lineHeight: 14,
  },
  itemOriginalPrice: {
    fontSize: 12,
    color: "#9E9E9E",
    textDecorationLine: "line-through",
  },
  itemFinalPriceRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "flex-end",
    gap: 4,
  },
  removeUnavailableButton: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#FF9800",
    borderRadius: 7,
    paddingVertical: 9,
    paddingHorizontal: 11,
    alignItems: "center",
    justifyContent: "center",
    maxWidth: 144,
    transform: [{ translateX: 10 }],
    cursor: "pointer",
  },
  removeUnavailableButtonText: {
    color: "#FF9800",
    fontSize: 12,
    fontWeight: "bold",
    textAlign: "center",
  },
  quantityControl: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#f5f5f5",
    borderRadius: 25,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  quantityButton: {
    backgroundColor: "#007AFF",
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  quantityButtonDelete: {
    backgroundColor: "#FF3B30",
  },
  quantityButtonDisabled: {
    opacity: 0.5,
  },
  quantityText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
    minWidth: 30,
    textAlign: "center",
  },
  checkoutCard: {
    backgroundColor: "#fff",
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    padding: 20,
    ...shadow("#000", { width: 0, height: 2 }, 0.05, 10, 3),
  },
  checkoutTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 18,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  totalLabel: {
    fontSize: 15,
    color: "#999",
  },
  totalPrice: {
    fontSize: 15,
    color: "#666",
  },
  savingsLabel: {
    fontSize: 15,
    color: "#4CAF50",
  },
  savingsPrice: {
    fontSize: 15,
    color: "#4CAF50",
    fontWeight: "600",
  },
  finalLabel: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#999",
  },
  finalPrice: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#666",
  },
  checkoutButton: {
    flexDirection: "row",
    backgroundColor: "#28a745",
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginTop: 8,
  },
  checkoutButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  loginHint: {
    textAlign: "center",
    color: "#FF3B30",
    fontSize: 13,
    marginTop: 12,
  },
  checkoutNote: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    marginTop: 16,
  },
  checkoutNoteText: {
    flex: 1,
    fontSize: 12,
    color: "#999",
    lineHeight: 20,
  },
  unavailableCheckoutNoteText: {
    flex: 1,
    fontSize: 12,
    color: "#FF3B30",
    lineHeight: 20,
  },
  emptyCartContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
    paddingHorizontal: 30,
    backgroundColor: "#fff",
    borderRadius: 20,
    marginTop: 20,
  },
  emptyCartTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
    marginTop: 20,
    marginBottom: 10,
  },
  emptyCartText: {
    fontSize: 15,
    color: "#999",
    textAlign: "center",
    marginBottom: 30,
    lineHeight: 22,
  },
  shopButton: {
    flexDirection: "row",
    backgroundColor: "#007AFF",
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  shopButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
});
