/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/basket`; params?: Router.UnknownInputParams; } | { pathname: `/book`; params?: Router.UnknownInputParams; } | { pathname: `/categories`; params?: Router.UnknownInputParams; } | { pathname: `/contact`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/myLibrary`; params?: Router.UnknownInputParams; } | { pathname: `/offers`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/temp`; params?: Router.UnknownInputParams; } | { pathname: `/../components/UI/ProfileItem`; params?: Router.UnknownInputParams; } | { pathname: `/support`; params?: Router.UnknownInputParams; } | { pathname: `/../components/pages/About copy/styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/pages/About copy 2/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/pages/About copy 2/styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/pages/Support/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/pages/Support/styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/about`; params?: Router.UnknownOutputParams; } | { pathname: `/basket`; params?: Router.UnknownOutputParams; } | { pathname: `/book`; params?: Router.UnknownOutputParams; } | { pathname: `/categories`; params?: Router.UnknownOutputParams; } | { pathname: `/contact`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/myLibrary`; params?: Router.UnknownOutputParams; } | { pathname: `/offers`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/temp`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/UI/ProfileItem`; params?: Router.UnknownOutputParams; } | { pathname: `/support`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/pages/About copy/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/pages/About copy 2/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/pages/About copy 2/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/pages/Support/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/pages/Support/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/about${`?${string}` | `#${string}` | ''}` | `/basket${`?${string}` | `#${string}` | ''}` | `/book${`?${string}` | `#${string}` | ''}` | `/categories${`?${string}` | `#${string}` | ''}` | `/contact${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/myLibrary${`?${string}` | `#${string}` | ''}` | `/offers${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/temp${`?${string}` | `#${string}` | ''}` | `/../components/UI/ProfileItem${`?${string}` | `#${string}` | ''}` | `/support${`?${string}` | `#${string}` | ''}` | `/../components/pages/About copy/styles${`?${string}` | `#${string}` | ''}` | `/../components/pages/About copy 2/index${`?${string}` | `#${string}` | ''}` | `/../components/pages/About copy 2/styles${`?${string}` | `#${string}` | ''}` | `/../components/pages/Support/index${`?${string}` | `#${string}` | ''}` | `/../components/pages/Support/styles${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/basket`; params?: Router.UnknownInputParams; } | { pathname: `/book`; params?: Router.UnknownInputParams; } | { pathname: `/categories`; params?: Router.UnknownInputParams; } | { pathname: `/contact`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/myLibrary`; params?: Router.UnknownInputParams; } | { pathname: `/offers`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/temp`; params?: Router.UnknownInputParams; } | { pathname: `/../components/UI/ProfileItem`; params?: Router.UnknownInputParams; } | { pathname: `/support`; params?: Router.UnknownInputParams; } | { pathname: `/../components/pages/About copy/styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/pages/About copy 2/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/pages/About copy 2/styles`; params?: Router.UnknownInputParams; } | { pathname: `/../components/pages/Support/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/pages/Support/styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
