/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/basket`; params?: Router.UnknownInputParams; } | { pathname: `/book`; params?: Router.UnknownInputParams; } | { pathname: `/booklist`; params?: Router.UnknownInputParams; } | { pathname: `/categories`; params?: Router.UnknownInputParams; } | { pathname: `/contact`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/invitation`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/myComments`; params?: Router.UnknownInputParams; } | { pathname: `/myFavorites`; params?: Router.UnknownInputParams; } | { pathname: `/myLibrary`; params?: Router.UnknownInputParams; } | { pathname: `/myLikes`; params?: Router.UnknownInputParams; } | { pathname: `/offers`; params?: Router.UnknownInputParams; } | { pathname: `/paymentRecords`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/rules`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/support`; params?: Router.UnknownInputParams; } | { pathname: `/temp`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/../components/UI/UserAddressList`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/about`; params?: Router.UnknownOutputParams; } | { pathname: `/basket`; params?: Router.UnknownOutputParams; } | { pathname: `/book`; params?: Router.UnknownOutputParams; } | { pathname: `/booklist`; params?: Router.UnknownOutputParams; } | { pathname: `/categories`; params?: Router.UnknownOutputParams; } | { pathname: `/contact`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/invitation`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/myComments`; params?: Router.UnknownOutputParams; } | { pathname: `/myFavorites`; params?: Router.UnknownOutputParams; } | { pathname: `/myLibrary`; params?: Router.UnknownOutputParams; } | { pathname: `/myLikes`; params?: Router.UnknownOutputParams; } | { pathname: `/offers`; params?: Router.UnknownOutputParams; } | { pathname: `/paymentRecords`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/rules`; params?: Router.UnknownOutputParams; } | { pathname: `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/support`; params?: Router.UnknownOutputParams; } | { pathname: `/temp`; params?: Router.UnknownOutputParams; } | { pathname: `/user`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/UI/UserAddressList`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/about${`?${string}` | `#${string}` | ''}` | `/basket${`?${string}` | `#${string}` | ''}` | `/book${`?${string}` | `#${string}` | ''}` | `/booklist${`?${string}` | `#${string}` | ''}` | `/categories${`?${string}` | `#${string}` | ''}` | `/contact${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/invitation${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/myComments${`?${string}` | `#${string}` | ''}` | `/myFavorites${`?${string}` | `#${string}` | ''}` | `/myLibrary${`?${string}` | `#${string}` | ''}` | `/myLikes${`?${string}` | `#${string}` | ''}` | `/offers${`?${string}` | `#${string}` | ''}` | `/paymentRecords${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/rules${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/support${`?${string}` | `#${string}` | ''}` | `/temp${`?${string}` | `#${string}` | ''}` | `/user${`?${string}` | `#${string}` | ''}` | `/../components/UI/UserAddressList${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/basket`; params?: Router.UnknownInputParams; } | { pathname: `/book`; params?: Router.UnknownInputParams; } | { pathname: `/booklist`; params?: Router.UnknownInputParams; } | { pathname: `/categories`; params?: Router.UnknownInputParams; } | { pathname: `/contact`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/invitation`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/myComments`; params?: Router.UnknownInputParams; } | { pathname: `/myFavorites`; params?: Router.UnknownInputParams; } | { pathname: `/myLibrary`; params?: Router.UnknownInputParams; } | { pathname: `/myLikes`; params?: Router.UnknownInputParams; } | { pathname: `/offers`; params?: Router.UnknownInputParams; } | { pathname: `/paymentRecords`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/rules`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/support`; params?: Router.UnknownInputParams; } | { pathname: `/temp`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/../components/UI/UserAddressList`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
